import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		double rnd = generator.nextDouble();

		int familiesNum = T;
		double firstBorn = rnd;
		double girlorboy= generator.nextDouble();
		int sum=1;

		double average=0;
		int twokids=0;
		int treekids=0;
		int fourormorekids=0;

		for(int i=0; i<familiesNum; i++){
			if(firstBorn>=0 && firstBorn<0.5){
		  	     while (girlorboy>0 && girlorboy<0.5) {
				    sum++;
				    girlorboy = generator.nextDouble();
			    }
			    sum++;
		    } else {
			     while (girlorboy>=0.5 && girlorboy<1) {
				    sum++;
			    	girlorboy = generator.nextDouble();
		    	}
			     sum++;
		    }
			average+=sum;
			if(sum==2) twokids++;
			if(sum==3) treekids++;
			if(sum>=4) fourormorekids++;
			firstBorn = generator.nextDouble();
			sum =1;
		}

		System.out.println("Average: "+ average/familiesNum + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: "+ twokids);
		System.out.println("Number of families with 3 children: "+ treekids);
		System.out.println("Number of families with 4 or more children: "+ fourormorekids);
		int maxin = Math.max(twokids, Math.max(treekids, fourormorekids));
		if(maxin==twokids) System.out.println("The most common number of children is 2.");
		if(maxin==treekids) System.out.println("The most common number of children is 3.");
		if(maxin==fourormorekids) System.out.println("The most common number of children is 4 or more.");
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		    
	}
}
